### ISSUE TITLE
A new column cannot have a not-null constraint

### ISSUE THREAD

**Issue by kketch** [fortunejs/fortune-postgres#11]
Currently the adapter attempts to alter existing tables and add missing columns, but it doesn't work if the table already has rows in it, and the new column is an array since the adapter try to apply a "not null" request to the column. 

Here's an example query generated by the adapter : 
> alter table "animal" add column "surnames" text[] not null

If there is preexisting rows in the table postgres will report the following error:
 > ERROR: column "surnames" contains null values

I'm not sure what should be done here, the not null constraint (if needed at all) could be added after adding the column and setting default values for preexisting rows, but this constraint may be not needed initially

**Comment by 0x8890** [comment]
The `NOT NULL` constraint is needed because fortune expects that when a field is an array, it is always an array, even if it is empty.

Not sure if this can be worked around, because when using `push` and `pull` operators, an array value is already expected to exist.

**Comment by kketch** [comment]
Yes but maybe it could be the adapter that always ensure that an array and not a null value is given to fortune ?
