### ISSUE TITLE
Number primaryKeyType not using numbers

### ISSUE THREAD

**Issue by bendman** [fortunejs/fortune-postgres#13]
Attempting to use the `Number` primaryKeyType does not actually product numbers.  It instead tries to create a record with the ID "YBL6QamdkjSeH6ncqpAX", which causes postgres to return an error (making me think the postgres schema is correct, but the ID generation is not).
#### Store Definition

``` javascript
const store = fortune({
  user: {
    email: { type: String },
    password: { type: String },
    name: { type: String }
  }
}, {
  adapter: [
    postgresAdapter,
    {
      url: `postgres://pguser:pgpass@${DB_URL.hostname}:${DB_URL.port}/pguser`,
      primaryKeyType: Number
    }
  ]
});
```
#### Response to a post

```
ERROR:  invalid input syntax for type double precision: "YBL6QamdkjSeH6ncqpAX"`
STATEMENT:  insert into "user" ("id", "email", "name", "password") values ($1, $2, $3, $4)
```

**Comment by 0x8890** [comment]
This is due to a bad default setting: it also expects to manually set `generatePrimaryKey` to `null`, if you want to use auto-incrementing integer primary keys. This should probably be patched so that you don't have to manually set this too.

**Comment by bendman** [comment]
I updated the store definition to be:

```javascript
const store = fortune({
  user: {
    email: { type: String },
    password: { type: String },
    name: { type: String }
  }
}, {
  adapter: [
    postgresAdapter,
    {
      url: `postgres://pguser:pgpass@${DB_URL.hostname}:${DB_URL.port}/pguser`,
      primaryKeyType: 'integer',
      generatePrimaryKey: null
    }
  ]
});
```

and I now get the following error:

```
ERROR:  null value in column "id" violates not-null constraint
DETAIL:  Failing row contains (null, test, null, test).
STATEMENT:  with inserted as (insert into "user" ("email", "name", "password") values ($1, $2, $3) returning id) select id from inserted
```

Is the store definition correct?  Also, is there anywhere that documents the values that are supposed to be used?

**Comment by 0x8890** [comment]
Oops, above comment had a small problem I think: `integer` should be `serial`.

There is a related issue #7.
