### ISSUE TITLE
Any plans for join tables for many-to-many?

### ISSUE THREAD

**Issue by itsravenous** [fortunejs/fortune-postgres#15]
As opposed to `integer[]` columns. Or any thoughts on why it's not worth implementing. I've read lots of conflicting opinions on join tables vs array columns for many to many relationships. I think I would be more comfortable with join tables (I've mainly worked with MySQL and SQLServer) but Fortune is such a good fit for my current needs I'm loathe to leave it for potentially unfounded worries.

**Comment by 0x8890** [comment]
From what I've heard, arrays are faster, or at least on par with join tables for performance. The only caveat is that Postgres doesn't have foreign key constraint for arrays, and there are no current plans for this feature.

**Comment by itsravenous** [comment]
Fair enough! I'll see how I get on :)
