### ISSUE TITLE
Delete resolve to early

### ISSUE THREAD

**Issue by thomasthiebaud** [fortunejs/fortune-postgres#18]
Hej, I have this tests 

```
  beforeEach(function () {
    return store.adapter.delete('user').then(() => {
      console.log('A');
      return store.adapter.delete('customer');
    }).then(() => console.log('B'));
  });

  describe('customers', function () {
    it('should create a default customer', function () {
      return database.addDefaultCustomer();
    });
  });

  describe('users', function () {
    it('should create a default user for the default customer', function () {
      console.log('C')
      return database.addDefaultCustomer()
        .then(() => database.addDefaultUser());
    });

    it('should add two users for the default customer', function () {
      console.log('D')
      return database.addDefaultCustomer()
        .then(() => database.addDefaultUser())
        .then(() => database.addAdminUser());
    });
  });
```

And I get this error on the first user test (the one with `console.log('C');`)
```
ConflictError: Unique constraint violated.
    at client.query [as callback] (node_modules/fortune-postgres/lib/index.js:360:27)
    at NativeQuery.handleError (node_modules/pg/lib/native/query.js:64:10)
    at after (node_modules/pg/lib/native/query.js:84:19)
    at onError (node_modules/pg-native/index.js:160:5)
    at Client._readError (node_modules/pg-native/index.js:81:8)
    at Client._read (node_modules/pg-native/index.js:121:19)
```

This error happened because the customer table is not properly truncated. But I'm sure that the `beforeEach` hook is executed before. Here is the order of the `console.log()` I get

```
A
B
C
```

which is correct. That is why I think the `store.adapter.delete()` function resolve to early. Is it a bug or did I miss something ?

**Comment by 0x8890** [comment]
The code for deletion is very simple, so simple that I wouldn't really know where the problem is: https://github.com/fortunejs/fortune-postgres/blob/4f827294bf5b100313c588bdebf4651abd11d030/lib/index.js#L465-L487

Maybe you can confirm that this is the case by adding a `find` before you got the ConflictError?

**Comment by 0x8890** [comment]
Also the test for the adapter does `create` immediately after `delete`: https://github.com/fortunejs/fortune/blob/44e0469e9c81516c96066b9fcea2607900ee0397/test/unit/adapter.js#L584-L585

**Comment by thomasthiebaud** [comment]
Ok, so I add a find before using delete like this
```
beforeEach(function () {
    return store.adapter.find('user').then((res) => {
      console.log('RES')
      console.log(res)
      return database.truncate()
    });
  });
```

I get this output 

```
RES
[ count: 0 ]
```

So there is not user. BUT if I go check in the database, there is one user (added throw fortunejs)

**Comment by thomasthiebaud** [comment]
If I'm switching from 

```
function truncate() {
  return store.adapter.delete('user')
      .then(() => store.adapter.delete('customer'));
}
```

to

```
function truncate() {
  return store.adapter.delete('customer')
      .then(() => store.adapter.delete('user'));
}
```

I not longer have the error, but I don't know why

**Comment by 0x8890** [comment]
Hmm, I'm not sure where the problem is, since the tests for this adapter seem to do what you're trying to do without error.

**Comment by thomasthiebaud** [comment]
Ok I found why :

- I was mixing `store.XYZ` and `store.adapter.XYZ`
- When you create a record using `store.adapter.create(type, records)`, records MUST be an array. Otherwise it will only call `return new Promise().resolve()`
- When adding data using `store.adapter.create` you have to manually insert relationship both in each parts. So in my case I had to put the customer id in `user.customer` and push the user id in the `customer.users`

**Comment by 0x8890** [comment]
Yup, Fortune.js handles relationships but the adapter doesn't.
