### ISSUE TITLE
Auto-generated IDs can sometimes have backslash in them

### ISSUE THREAD

**Issue by jmeas** [fortunejs/fortune-postgres#21]
I was playing around with CRUD'ing some resources with fortune-postgres+the JSON API adapter, and an ID was generated like this:

`"PDyp40Yu/lUBSHbhvtuP"`

This seems unexpected, as I'd need to encode the ID to send it over the wire. I'm using some generic JSON API code on the client, and it produces incorrect requests from this ID; such as

`DELETE /things/PDyp40Yu/lUBSHbhvtuP`

@daliwali , if I updated [this ID generation logic](https://github.com/fortunejs/fortune-postgres/blob/4914aa1a26a014096d7e86f4df388448721059fd/lib/helpers.js#L102-L104) to ensure that `/` are never created, would you be :+1: to that change?

**Comment by daliwali** [comment]
Argh, okay I'm fine with changing it. But it should be the other way around: broken clients should fix their implementation by properly encoding URIs                              :(

**Comment by jmeas** [comment]
If you instead think that `/` should be an acceptable character for an ID, then I'm alright with that, too. I can just as easily update any other lib.

If we decide to keep it, then I think it should be documented (I can update the docs for that, too).

What do you think is best?

**Comment by daliwali** [comment]
There is specifically a test that `/` in an ID works: https://github.com/fortunejs/fortune-http/blob/c0dd4fa04ca60b1048eb269c96dbb503ad4f3489/test/json.js#L52

I think it's ok to change ID generation here, most clients are not smart enough to encode URIs apparently. However, for hypermedia clients that must use URIs from the server, this would be impossible.

**Comment by jmeas** [comment]
Cool – I'll whip up a PR soon.
