### ISSUE TITLE
Sharing DB connections with the rest of the app

### ISSUE THREAD

**Issue by jmeas** [fortunejs/fortune-postgres#22]
Often times, a RESTful API is just one thing that accesses a DB in an app. Atm, there's no way to share the same pool of connections between fortune and other things in your app that may connect that I can find.

For instance, in a simple app, I've got three separate things that access the database:

1. a library for managing user sessions
2. some code in my server, unrelated to any lib or framework
3. fortune-postgres

Due to 2, I make a pg connection myself. Then, the lib I'm using for 1 has a hook to pass it a `pg` instance, so that the connection can be shared between those two – that lib doesn't make its own pool of clients using pg. But fortune-postgres only accepts a URL, so it creates a new instance of pg, and therefore, a new set of connections.

I know it's nice to abstract away the underlying npm module, but exposing a `pg` option as an alternative to `url` would be useful, I think.

---

Another option would be letting devs pass in more pg options, so that `store.adapter.client` could be used for other connections.

**Comment by daliwali** [comment]
There are two new options:

- `connection`: a connection object that can be used instead of `url`.
- `pool`: an instance of `node-pg-pool` can be passed in directly.

https://github.com/fortunejs/fortune-postgres/commit/644c3ba1de31553b77cf0b1544b52f7c2f13cab4.

**Comment by jmeas** [comment]
Thanks! 👌
