### ISSUE TITLE
Error when no database named "postgres" exists

### ISSUE THREAD

**Issue by seanCodes** [fortunejs/fortune-postgres#27]
I'm trying to connect to a database hosted on Heroku and keep getting the error `permission denied for database "postgres"`. Looking at the source code, it seems this plugin attempts to create a connection to a [database named "postgres"](https://github.com/fortunejs/fortune-postgres/blob/master/lib/index.js#L102) before connecting to the specified database (so the database can be created if necessary). This is problematic when using Heroku, since database names are automatically generated for you and it's not possible to change them. 😕 

Is there a workaround for this or is having a DB named "postgres" a requirement?

**Comment by jmeas** [comment]
@seanCodes **[here is an example app](https://github.com/jmeas/moolah)** that uses Fortune with Postgres + Heroku. I don't think I did anything special, but I figured I'd post it here as a reference.

I might have time to look into this more, but for now feel free to explore that project to see if it helps at all.

**Comment by seanCodes** [comment]
@jmeas Thanks for the quick response!

I took a look at your sample app and it looks like you're using v1.4.7 of `fortune-postgres`. According to the git blame, the line I'm having trouble with was introduced in v1.6.0 by commit 251b086, which is probably why it's now popping up for me.

**Comment by jmeas** [comment]
Makes sense, @seanCodes . It has been awhile since I've worked on that app. I've got a busy week ahead, but if I end up having time over the next few days, I'll try upgrading to the latest to see what happens. Sorry that you're running into this issue!

**Comment by seanCodes** [comment]
No problem, if I can fix it myself I'll submit a PR. In the mean time I can just downgrade to 1.4.7 until the the fix is in. Thanks for looking into it!

**Comment by daliwali** [comment]
Ahh crap. This is my fault for [assuming that a `postgres` database exists](https://stackoverflow.com/questions/2370525/default-database-named-postgres-on-postgresql-server). The reason why it's done is so that any connection can be established in order to ensure that the specified database exists. I think a possible solution is to use another default database, namely `template0`.

**Comment by seanCodes** [comment]
@daliwali I think assuming any default database exists might be a problem, especially for Heroku DBs, where all database names are random. 🙁

A fix for this particular issue might be to test first if the user-specified database exists, and if not, then attempt to connect to a default database like `postgres` or `template0` to create it.

**Comment by daliwali** [comment]
This has been fixed: https://github.com/fortunejs/fortune-postgres/commit/4174a58c1edfb87b94f55c7cde7da96e12682f7a

It still checks before attempting to connect to the specified database, it just swallows any errors that may occur now.
