### ISSUE TITLE
DB migrations

### ISSUE THREAD

**Issue by ct-dali** [fortunejs/fortune-postgres#3]
Currently tables are initialized once and not touched again. Need to add, drop, & modify columns based on type definitions if they changed.

**Comment by killercup** [comment]
I was also wondering about that. It'd probably use [knex](http://knexjs.org/#Migrations) for this right now.

**Comment by 0x8890** [comment]
On second thought, dropping/modifying data here might be too dangerous, so maybe only add columns here.

**Comment by 0x8890** [comment]
Addressed in commit https://github.com/fortunejs/fortune-postgres/commit/86b9d1a2b826886454fd593edeec8c1556f442ce, published as `1.0.6`.
