### ISSUE TITLE
fortune-postgres 1.6.9 is not compatible with node 8.x LTS

### ISSUE THREAD

**Issue by provpup** [fortunejs/fortune-postgres#31]
Hello,

I was upgrading my fortune-postgres dependency from 1.6.5 to 1.6.9 using node 8.x LTS, but it cannot be upgraded:

error fortune-postgres@1.6.9: The engine "node" is incompatible with this module. Expected version ">=10".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Is node 10.x now necessary for running fortune-postgres?

Thanks!

**Comment by daliwali** [comment]
No, it is not required. Feel free to ignore this error, I will remove that from `package.json`.
