### ISSUE TITLE
Default ID Generation

### ISSUE THREAD

**Issue by ntuanb** [fortunejs/fortune-postgres#6]
Hi, 

Is there a way to let the database generate the ID?

At the moment, it seems that the ID is created manually with the generatePrimaryKey. 

Thanks.

**Comment by 0x8890** [comment]
Currently not, it's done here: https://github.com/fortunejs/fortune-postgres/blob/1dd26511eaaad165823518791e2591b68c45d86b/lib/helpers.js#L33

PR would be welcome.

**Comment by 0x8890** [comment]
Done in this commit https://github.com/fortunejs/fortune-postgres/commit/df774dbdcca6869a08ad239737876720f77021f6.
